DROP TABLE IF EXISTS Users cascade;

CREATE TABLE Users (
    id        INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      TEXT,
    email     TEXT        UNIQUE,
    otp       TEXT,
    attempt   INTEGER
);

INSERT INTO Users (id, name, email) VALUES (1, 'James', 'tsuisauchi.tsc@gmail.com');